spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/websocket
    username: websocket
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 60399556172-q3mclot3j6cfh220ahivpr5c8l1gq73p.apps.googleusercontent.com
            client-secret: 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

  data:
    mongodb:
      uri: mongodb://localhost:8282/backgammon



logging:
  level:
    com.example: DEBUG